spring:
  datasource:
    url: jdbc:mysql:///mall1909?serverTimezone=GMT%2B8
    username: root
    password: mz666672
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml


